### PR TITLE
Converted some tests from `pytest` into vanilla `unittest`

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by fjarri** [comment]
Repeating my comment in the previous PR: Is running tests via `pytest` such a big problem? Pytest has a lot of functionality that comes in handy, parametrization, convenient test filtering and what have you. I would much rather keep it. I haven't seen any Python project using `unittest`. The mentioned `monkeytype` seems like it would introduce more problems than it can possibly solve; I've started the typing work, and it's not trivial to come up with correct annotations. Plus, I'd rather put in the annotations that the function *should have* and then see if it's called correctly, rather than going in the opposite direction.

**Comment by KOLANICH** [comment]
>Repeating my comment in the previous PR: Is running tests via pytest such a big problem?

It is terribly slow. At least on my machine. Just calling `python3 ./tests/test_something.py` works much faster. Yes, it doesn't have a fancy GUI and XML reports GitLab loves, but when developing on localhost the most crucial thing is to reduce the delay, because one has to run tests a lot of times and exen the delay not very significant in one run multiplies by the count of runs.

>Pytest has a lot of functionality that comes in handy, parametrization, convenient test filtering and what have you.

The functionality of the CLI tool can be used with `unittest`-style tests. Probably `subTest` will lack executability of the certain test case, but the usual tests with `assert`s feel like that can be replaced with the equivalent functionality of `unittest`. It may look not as fancy as with the `assert` keyword, but again, fanciness is not less important than the practical advantages of `unittest` mentioned.

>The mentioned monkeytype seems like it would introduce more problems than it can possibly solve

The annotations generated by the `monkeytype` are just a good starting point, they are intended to be refactored by human. But having automated generation of annotations is a good thing. There were quite some cases in my projects (in small ones, for bigger ones I don't even bother to add them manually and rely entirely on `monkeytype` to do it) I was sure I had added them manually everywhere possible, the tool still has found the places I had missed them. Anyswy, AFAIK there is a plugin for `pytest` to make it run `monkeytype` for tests, but again, I think that if it is feasible to write tests in vanilla `unittest`, then it should be done this way.

**Comment by fjarri** [comment]
> It is terribly slow. At least on my machine.

On my laptop (definitely far from being the fastest one in existence), running `py.test -k some_test` takes 0.6s. The whole test suite takes under 2s. I think it is acceptable. 

>  It may look not as fancy as with the assert keyword, but again, fanciness is not less important than the practical advantages of unittest mentioned.

It is not about fanciness, it's about convenience and readability. 

>  I was sure I had added them manually everywhere possible, the tool still has found the places I had missed them.

There's a simple solution to that: `mypy --strict`. I already do it in a couple of my other projects, and I do want to bring `peval` to the level where it would pass for it too. 

I understand that you put a decent amount of work into this, and I delayed the decision thinking I might come to accept using unittest, but I just cannot. I'm sorry, I don't see any redeeming qualities of it.

**Comment by KOLANICH** [comment]
No problem. Thanks anyway :)

**Pull request closed without merging**
